/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RecentJobsRouteImport } from './routes/recent-jobs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewUserRouteImport } from './routes/new-user'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobRouteImport } from './routes/job'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentJobsRoute = RecentJobsRouteImport.update({
  id: '/recent-jobs',
  path: '/recent-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewUserRoute = NewUserRouteImport.update({
  id: '/new-user',
  path: '/new-user',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobRoute = JobRouteImport.update({
  id: '/job',
  path: '/job',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/job': typeof JobRoute
  '/login': typeof LoginRoute
  '/new-user': typeof NewUserRoute
  '/profile': typeof ProfileRoute
  '/recent-jobs': typeof RecentJobsRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/job': typeof JobRoute
  '/login': typeof LoginRoute
  '/new-user': typeof NewUserRoute
  '/profile': typeof ProfileRoute
  '/recent-jobs': typeof RecentJobsRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/job': typeof JobRoute
  '/login': typeof LoginRoute
  '/new-user': typeof NewUserRoute
  '/profile': typeof ProfileRoute
  '/recent-jobs': typeof RecentJobsRoute
  '/resume': typeof ResumeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/job'
    | '/login'
    | '/new-user'
    | '/profile'
    | '/recent-jobs'
    | '/resume'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/job'
    | '/login'
    | '/new-user'
    | '/profile'
    | '/recent-jobs'
    | '/resume'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/job'
    | '/login'
    | '/new-user'
    | '/profile'
    | '/recent-jobs'
    | '/resume'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JobRoute: typeof JobRoute
  LoginRoute: typeof LoginRoute
  NewUserRoute: typeof NewUserRoute
  ProfileRoute: typeof ProfileRoute
  RecentJobsRoute: typeof RecentJobsRoute
  ResumeRoute: typeof ResumeRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent-jobs': {
      id: '/recent-jobs'
      path: '/recent-jobs'
      fullPath: '/recent-jobs'
      preLoaderRoute: typeof RecentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-user': {
      id: '/new-user'
      path: '/new-user'
      fullPath: '/new-user'
      preLoaderRoute: typeof NewUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job': {
      id: '/job'
      path: '/job'
      fullPath: '/job'
      preLoaderRoute: typeof JobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JobRoute: JobRoute,
  LoginRoute: LoginRoute,
  NewUserRoute: NewUserRoute,
  ProfileRoute: ProfileRoute,
  RecentJobsRoute: RecentJobsRoute,
  ResumeRoute: ResumeRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
